apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: web
        image: ghcr.io/tkubica12/web:1
        ports:
        - containerPort: 3000
