apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  selector:
    matchLabels:
      app: service3
  replicas: 1
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: web
        image: ghcr.io/tkubica12/web:1
        ports:
        - containerPort: 3000
