apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: web
        image: ghcr.io/tkubica12/web:1
        ports:
        - containerPort: 3000
