---
- name: Create Azure resources
  hosts: localhost
  # connection: local
  # gather_facts: no

  vars:
    rg_name: myResourceGroup
    location: westeurope
    vnet_name: myVnet
    subnet_name: mysubnet
    address_prefix: 10.0.0.0/16
    subnet_prefix: 10.0.0.0/24

  collections:
    - azure.azcollection

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ rg_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ address_prefix }}"

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ rg_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_prefix }}"
        virtual_network_name: "{{ vnet_name }}"

