name: Scan Terraform manifests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    environment: demo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'azure'
        only_warn: false
        sarif_upload: true
        iac_dir: 'long_introductions/infrastructure_as_code/terraform_full_demo'

