name: Generate terraform docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'
jobs:
  docs:
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Render terraform docs README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./long_introductions/infrastructure_as_code/terraform_full_demo/
        output-file: README.md
        output-method: replace
        git-push: "false"

    - name: Commit and push README.md
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./long_introductions/infrastructure_as_code/terraform_full_demo/README.md
        git commit --allow-empty -m "Autogenerated documentation"
        git push origin HEAD:${{ github.ref }}