name: Generate Terraform plan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
      run: terraform init -upgrade 

    - name: Terraform Plan
      working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
      run: terraform plan -out=tfplan  

    - name: Store plan as artefact
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: ./long_introductions/infrastructure_as_code/terraform_full_demo/tfplan
