name: Deploy infrastructure using Terraform
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'
    
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download plan from artefacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: iac_plan.yaml
          workflow_conclusion: success
          name: plan
          path: ./long_introductions/infrastructure_as_code/terraform_full_demo
          check_artifacts:  false
          search_artifacts: false

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
        working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
        run: terraform init


      - name: Terraform apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
        working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
        run: terraform apply -auto-approve  tfplan