name: Get Terraform plan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Install Azure cli
      run: |
        sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install -y azure-cli

    - name: Azure Login
      run: az login --identity

    - name: Install dependencies
      run: sudo apt-get install -y unzip

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
      run: terraform init -upgrade 

    - name: Terraform Plan
      working-directory: ./long_introductions/infrastructure_as_code/terraform_full_demo
      run: |
        terraform plan -out=tfplan  

    - name: Store plan as artefact
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan
