name: Generate terraform docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/infrastructure_as_code/terraform_full_demo/**'
jobs:
  docs:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./long_introductions/infrastructure_as_code/terraform_full_demo/
        output-file: README.md
        output-method: replace
        git-push: "true"