name: Check Kubernetes manifests security
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/kubernetes/**'

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov
    environment: demo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Render Kubernetes manifests
      id: render
      uses: bridgecrewio/k8s-render@master
      with:
        directory: long_introductions/kubernetes/helm/charts/web

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: long_introductions/kubernetes/helm/charts/web