name: kubelinter
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/kubernetes/**'

jobs:
  kubelinter:
    runs-on: ubuntu-latest
    name: kubelinter
    environment: demo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Render manifests
      run: |
        mkdir ./rendered
        helm template -f long_introductions/kubernetes/helm/environments/prod/values.yaml ./long_introductions/kubernetes/helm/charts/web > ./rendered/rendered.yaml

    - name: Scan repo with kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      with:
        directory: ./rendered
        format: plain