name: kubeval
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/kubernetes/**'

jobs:
  kubeval:
    runs-on: ubuntu-latest
    name: kubeval
    environment: demo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: test
      uses: desaintmartin/helm-kubeval-action@master
      with:
        path: ./long_introductions/kubernetes/helm/charts/web