name: Kubernetes - Checkov
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'long_introductions/kubernetes/**'

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov
    environment: demo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Render manifests
      run: |
        mkdir ./rendered
        helm template -f long_introductions/kubernetes/helm/environments/prod/values.yaml ./long_introductions/kubernetes/helm/charts/web > ./rendered/rendered.yaml

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: kubernetes
        directory: ./rendered